module.exports = {
    homepage: './assets/js/home/homepage/HomePage.jsx',
    profile: './assets/js/userprofile/profile/Profile.jsx',
    educator: './assets/js/home/creator/Educator.jsx',
    register: './assets/js/authentication/register/Register.jsx',
    login: './assets/js/authentication/login/Login.jsx',
    createclass: './assets/js/classroom/createclass/CreateClass.jsx',
    classroom: './assets/js/classroom/classroom/Classroom.jsx',
    singlevideo: './assets/js/singlevideo/singlevideoview/SingleVideoPage.jsx',
    upload: './assets/js/upload/upload/UploadSingleVideo.jsx',
    createseries: './assets/js/series/create/CreateSeries.jsx',
    seriespage: './assets/js/series/seriespage/SeriesPage.jsx',
    seriesviewer: './assets/js/series/seriesviewer/SeriesViewer.jsx',
    quizaddingform: './assets/js/testinggrounds/QuizAddingForm/QuizAddingForm.jsx',
}