# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20160613_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('is_private', models.BooleanField(default=False)),
                ('access_code', models.CharField(default='', max_length=100)),
                ('avg_rating', models.IntegerField(default=0)),
                ('avg_length_videos', models.IntegerField(default=0)),
                ('avg_topics_videos', models.IntegerField(default=0)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_series', to='backend.CustomUser')),
                ('students', models.ManyToManyField(related_name='student_series', to='backend.CustomUser')),
                ('tas', models.ManyToManyField(related_name='ta_series', to='backend.CustomUser')),
            ],
        ),
        migrations.CreateModel(
            name='SeriesFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('stars', models.IntegerField(default=1)),
                ('comment', models.TextField(blank=True, null=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_feedbacks', to='backend.Series')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_feedbacks', to='backend.CustomUser')),
            ],
        ),
        migrations.CreateModel(
            name='SeriesVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='creators',
        ),
        migrations.RemoveField(
            model_name='video',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='video',
            name='order',
        ),
        migrations.RemoveField(
            model_name='video',
            name='unit',
        ),
        migrations.AddField(
            model_name='classroom',
            name='creator',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='created_classrooms', to='backend.CustomUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='creator',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='video_uploads', to='backend.CustomUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seriesvideo',
            name='video',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='backend.Video'),
        ),
        migrations.AddField(
            model_name='classroomvideo',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='backend.Classroom'),
        ),
        migrations.AddField(
            model_name='classroomvideo',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='backend.Unit'),
        ),
        migrations.AddField(
            model_name='classroomvideo',
            name='video',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_video', to='backend.Video'),
        ),
    ]
