# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-30 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_customuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='num_questions',
            field=models.IntegerField(default=0),
        ),
    ]
