# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-30 21:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_video_num_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='num_questions',
            new_name='question_counter',
        ),
    ]
