# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-07 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_question_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
