# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-13 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_auto_20160712_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresponse',
            name='endorsed',
            field=models.BooleanField(default=False),
        ),
    ]
