# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-14 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_questionresponse_endorsed'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSeriesData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_data', to='backend.Series')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_data', to='backend.CustomUser')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSeriesVideoData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_views', models.IntegerField(default=0)),
                ('avg_duration_watched', models.IntegerField(default=0)),
                ('seconds_into_video', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('sp_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos_data', to='backend.StudentSeriesData')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_students_data', to='backend.Video')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSeriesVideoQuizQuestionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(default='')),
                ('is_correct', models.BooleanField(default=False)),
                ('context', models.CharField(default='', max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('quiz_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='backend.QuizQuestion')),
                ('scv_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes_data', to='backend.StudentSeriesVideoData')),
            ],
        ),
        migrations.RemoveField(
            model_name='studentclassvideoquizquestiondata',
            name='quiz_question',
        ),
        migrations.RemoveField(
            model_name='studentclassvideoquizquestiondata',
            name='scv_data',
        ),
        migrations.DeleteModel(
            name='StudentClassVideoQuizQuestionData',
        ),
    ]
