# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-14 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_auto_20160714_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentseriesvideodata',
            old_name='sp_data',
            new_name='ss_data',
        ),
        migrations.RenameField(
            model_name='studentseriesvideoquizquestiondata',
            old_name='scv_data',
            new_name='ssv_data',
        ),
    ]
