# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-14 18:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_studentseriesvideodata_watched'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentseriesvideodata',
            old_name='avg_duration_watched',
            new_name='total_time_watched',
        ),
    ]
