# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-19 15:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_auto_20160718_1731'),
        ('backend', '0029_auto_20160719_1542'),
    ]

    operations = [
    ]
