# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-25 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_interesteduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
