# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-26 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_video_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='curated',
            field=models.BooleanField(default=False),
        ),
    ]
