# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-15 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0034_studentseriesvideodata_mastered'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='googleId',
            field=models.CharField(default='', max_length=300),
        ),
    ]
