# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-05 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0034_studentseriesvideodata_mastered'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breakpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
                ('text', models.TextField(blank=True, null=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakpoints', to='backend.Video')),
            ],
        ),
        migrations.CreateModel(
            name='BreakpointQuizQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MC', 'Mulitple Choice'), ('TF', 'True/False'), ('FR', 'Free Response')], default='MC', max_length=2)),
                ('breakpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='backend.Breakpoint')),
            ],
        ),
        migrations.AlterField(
            model_name='mcchoice',
            name='quiz_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mc_responses', to='backend.QuizQuestion'),
        ),
        migrations.AlterField(
            model_name='studentseriesvideoquizquestiondata',
            name='quiz_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='backend.QuizQuestion'),
        ),
        migrations.AddField(
            model_name='mcchoice',
            name='breakpoint_quiz_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mc_responses', to='backend.BreakpointQuizQuestion'),
        ),
        migrations.AddField(
            model_name='studentseriesvideoquizquestiondata',
            name='breakpoint_quiz_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='breakpoint_questions', to='backend.BreakpointQuizQuestion'),
        ),
    ]
