# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-05 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0035_auto_20160805_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breakpointquizquestion',
            name='breakpoint',
        ),
        migrations.AlterModelOptions(
            name='breakpoint',
            options={'ordering': ['time']},
        ),
        migrations.RemoveField(
            model_name='mcchoice',
            name='breakpoint_quiz_question',
        ),
        migrations.RemoveField(
            model_name='studentseriesvideoquizquestiondata',
            name='breakpoint_quiz_question',
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='breakpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='backend.Breakpoint'),
        ),
        migrations.AlterField(
            model_name='mcchoice',
            name='quiz_question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mc_responses', to='backend.QuizQuestion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='backend.Video'),
        ),
        migrations.AlterField(
            model_name='studentseriesvideoquizquestiondata',
            name='quiz_question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='backend.QuizQuestion'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BreakpointQuizQuestion',
        ),
    ]
